### PR TITLE
Fix resource pack compatibility

### LINKED ISSUE #16: Dirt dots with resource packs
I am using a 128x resource pack (Monsterley HD) which, like thousands of others, will likely never add support for this mod.
Therefore I suggest not adding the dirt dots by the mod and instead just attempt to cut the textures as well as you can (either from `dirt` or the top of `grass_top_side`)

### PR DESCRIPTION
**Pull request by Madis0**
Improves the default textures to make sure they look better in all kinds of resource packs. Yeah, 128x should not be as "blocky" but it is still better than having default-looking lines on top of the blocks...

[Images before and after](https://imgur.com/a/X1rbCeN)

Alternatively, you may want to enable the default-overlays only when the Default resource pack is on top.

Fixes #16

### CODE REVIEW

**Comment by LambdAurora** [comment]
This mod has custom data files in resource packs for a reason: for custom resource packs to be made to fix those issues.

This PR dramatically decreases the quality of some of the grass connections with the Default resource pack, which I really don't like.

> Alternatively, you may want to enable the default-overlays only when the Default resource pack is on top.
This is a much more complicated issue though, not because the Default not on top that it means the grass textures are changed, a pack can be model tweaks, entity textures and stuff.

Having a default enabled built-in resource pack could help, sadly resource packs are not capable of that unless it's a first start, which is highly problematic.

This PR could be offered as a resource pack, or as a "compat mode" built-in resource pack to use in combination with other resource packs if the defaults don't mix in well.

> Yeah, 128x should not be as "blocky" but it is still better than having default-looking lines on top of the blocks...

128x mask textures can be made to reduce the "blocky" effect. It was planned to have a default 32x built-in resource pack for the masks and other specific textures.

**Comment by Madis0** [comment]
> This PR could be offered as a resource pack, or as a "compat mode" built-in resource pack to use in combination with other resource packs if the defaults don't mix in well.

Okay, I went with this approach. However, it doesn't appear on the resource pack list, nor does it work when copied to resourcepacks folder manually.

**Comment by LambdAurora** [comment]
> Okay, I went with this approach. However, it doesn't appear on the resource pack list, nor does it work when copied to resourcepacks folder manually.

That's because this line is required `ResourceManagerHelper.registerBuiltinResourcePack(mc("compat"), modContainer, ResourcePackActivationType.NORMAL);` in the mod entrypoint.
[Which is here](https://github.com/LambdAurora/LambdaBetterGrass/blob/1.17/src/main/java/dev/lambdaurora/lambdabettergrass/LambdaBetterGrass.java#L53)

**Comment by Madis0** [comment]
Thanks, it appears now but only the grass seems to be fixed (due to texture change), the JSONs seem to get overridden by the default pack (even though I disabled it on resource packs screen).

**Comment by Madis0** [comment]
I am still struggling to get the JSON to work here, any ideas? I felt like maybe introducing an empty "overrides" node to mycelium would help, but no. Also, disabling the default extension on resource packs list made no difference...

**Comment by LambdAurora** [comment]
Ok, after some thought this PR will not be merged.

But a variant allowing for the better compatibility will be done once this mod is ported to Quilt. This port will allow built-in resource packs to tell "hey, I want to be enabled by default, but I still can be disabled and so respect the user's choice", this is the best option imo.

The idea will be to move the incompatible parts to a built-in resource pack that is enabled by default, so if someone uses a resource pack they will be able to disable the built-in one.

**Pull request closed without merging**
